region                   = "us-east-2"
zone                     = "us-east-2a"
n_workers                = "3"
n_controllers            = "3"
worker_instance_type     = "t2.small"
controller_instance_type = "t2.small"
